### ISSUE TITLE
ESDoc not usable after last update

### ISSUE THREAD

**Issue by Timbuktu1982** [EnterTheNameHere/esdoc-monorepo#15]
TypeError: Cannot use 'in' operator to search for 'length' in null
    at initialize (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/cheerio/lib/load.js:105:28)
    at IceCap._filter (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/ice-cap/out/IceCap.js:400:40)
    at IceCap._nodes (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/ice-cap/out/IceCap.js:382:25)
    at IceCap.text (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/ice-cap/out/IceCap.js:122:22)
    at IdentifiersDocBuilder._buildLayoutDoc (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-publish-html-plugin/out/Builder/DocBuilder.js:243:11)
    at IdentifiersDocBuilder.exec (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-publish-html-plugin/out/Builder/IdentifiersDocBuilder.js:25:20)
    at Plugin._exec (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-publish-html-plugin/out/Plugin.js:63:68)
    at Plugin.onPublish (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-publish-html-plugin/out/Plugin.js:45:10)
    at PluginManager._execHandler (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-core/lib/Plugin/PluginManager.js:165:24)
    at PluginManager.onPublish (/usr/local/lib/node_modules/@enterthenamehere/esdoc-standard-plugin/node_modules/@enterthenamehere/esdoc-core/lib/Plugin/PluginManager.js:291:10)

**Comment by EnterTheNameHere** [comment]
Ah, the cheerio broke everything again... I've set the version to the working one and published update. The package manager should now point to the correct cheerio version.

If it persist, clearing node_modules and doing install should make it work.

**Comment by Timbuktu1982** [comment]
Works fine. Thank you
